Feature 20 - Add select for currencies
Platzi-Master-C8/gethired-jobplacement-salaries-frontend pull request #21
Opened 2022-01-14 17:28 UTC by yadurani

## Checklist

- [x] I have followed the [contributor guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md)
- [ ] Tests are included
- [ ] Documentation is changed or added
- [x] Related issue has been created
- [x] Commits messages follows [commit guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md/#Commits)

### Type of PR

- [x] Feature
- [ ] Bugfix
- [ ] Hotfix
- [ ] Chore

### Merge strategy

- [x] Squash (default)
- [ ] Merge commit (branch merges, usually used for merges to master)
- [ ] Rebase (preserve individual commits without merge commit)

### Purpose
Create a input to select currency
> Enlist the purposes or write an abastract about it, please be detailed, remember that not all the members of the team have the context of yout tasks
### Relevant tickets

> Paste here the link to the task ticket
resolves [#20]

### Related PR's

> Paste here the links to related PR's
### Screenshots

> Add screenshots that could help others do understand even more the objective of your pr
<img width="545" alt="Screen Shot 2022-01-14 at 12 27 38 PM" src="https://user-images.githubusercontent.com/25048114/149558740-ca16090a-3ac2-44c7-9c9b-09cc1f513b63.png">

2022-01-14 22:25 UTC, kevfarid requested changes

2022-01-14 22:25 UTC, kevfarid commented on src/constants/index.js
> +export const ListCurrencies = ['USD', 'AED', 'AFN', 'ALL', 'AMD', 'ANG'];
You should create a service for the list of currencies. you can't burn this data for it would change in the future

2022-01-15 16:53 UTC, johannpereze requested changes
I just saw one little thing to change 😆

2022-01-15 16:53 UTC, johannpereze commented on src/components/TabCalculate/TabCalculate.jsx
> +import { selectCurrency } from '../../app/CalculateSalary/selectors';
Change to relative path, please

2022-01-15 16:54 UTC, johannpereze commented on src/components/TabCalculate/TabCalculate.jsx
> +import { selectCurrency } from '../../app/CalculateSalary/selectors';
Even better, move it to line 16 :D

2022-01-29 17:33 UTC, kevfarid approved these changes
Nice <3

2022-01-29 18:06 UTC, johannpereze approved these changes
LGTM

2022-01-31 11:36 UTC, merged