Feature 26 - Show error messages when the query for the chart data to the API fails
Platzi-Master-C8/gethired-jobplacement-salaries-frontend pull request #27
Opened 2022-01-19 02:06 UTC by johannpereze

## Checklist

- [x] I have followed the [contributor guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md)
- [] Tests are included
- [ ] Documentation is changed or added
- [x] Related issue has been created
- [x] Commits messages follows [commit guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md/#Commits)

### Type of PR

- [x] Feature
- [ ] Bugfix
- [ ] Hotfix
- [ ] Chore

### Merge strategy

- [x] Squash (default)
- [ ] Merge commit (branch merges, usually used for merges to master)
- [ ] Rebase (preserve individual commits without merge commit)

### Purpose

When there is a problem with the response of the server, as a user you should know there was an error and what you should do

> Enlist the purposes or write an abastract about it, please be detailed, remember that not all the members of the team have the context of yout tasks
### Relevant tickets

> Paste here the link to the task ticket
resolves [#26 ]

### Related PR's

> Paste here the links to related PR's
### Screenshots

> Add screenshots that could help others do understand even more the objective of your pr

2022-01-22 23:17 UTC, kevfarid requested changes

2022-01-22 23:17 UTC, kevfarid commented on src/app/CalculateSalary/slice.js
> +    // Triggers rejection if the fetch fails or return anything diferent to the salaries values
Delete this comment

2022-01-22 23:17 UTC, kevfarid commented on src/app/CalculateSalary/slice.js
> +    // Triggers rejection if the fetch fails or return anything diferent to the salaries values
Delete this comment

2022-01-24 15:51 UTC, yadurani submitted a review, later dismissed

2022-01-24 18:29 UTC, yadurani approved these changes

2022-01-25 00:05 UTC, kevfarid approved these changes

2022-01-25 00:05 UTC, merged